
  

server:
 port: 8080

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DB_Host:localhost}:3306/productdb
    username: root 
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  application:
    name: PRODUCT-SERVICE
    
  config:
     import: 
     CONFIG_SERVICE: http://${CONFIG_SERVICE_URL:localhost}:9296 
 
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}    

